"""Cross-run memory helpers for AI Loop."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .artifacts import now_iso, read_json


def record_run_memory(run_dir: Path) -> None:
    """Append or replace this run in the repository-level JSONL index."""
    run_path = run_dir / "run.json"
    if not run_path.exists():
        return
    run_data = read_json(run_path)
    repo_value = run_data.get("repo")
    if not repo_value:
        return
    repo = Path(str(repo_value))
    artifacts_root = run_dir.parent
    index_path = artifacts_root / "index.jsonl"
    record = build_record(run_dir, run_data)
    upsert_jsonl_record(index_path, record)
    write_state_markdown(artifacts_root)


def build_record(run_dir: Path, run_data: dict[str, Any]) -> dict[str, Any]:
    summary_path = str(run_data.get("summary_path") or "summary.md")
    return {
        "schema_version": 1,
        "run_id": str(run_data.get("run_id") or run_dir.name),
        "mode": str(run_data.get("mode") or "run"),
        "status": str(run_data.get("status") or "UNKNOWN"),
        "error_code": str(run_data.get("error_code") or ""),
        "exit_code": run_data.get("exit_code"),
        "task_file": str(run_data.get("task_file") or ""),
        "summary_path": f"{run_dir.name}/{summary_path}",
        "patch_paths": [f"{run_dir.name}/{path}" for path in run_data.get("patch_paths") or []],
        "updated_at": str(run_data.get("updated_at") or now_iso()),
        "finished_at": run_data.get("finished_at"),
    }


def upsert_jsonl_record(index_path: Path, record: dict[str, Any]) -> None:
    index_path.parent.mkdir(parents=True, exist_ok=True)
    records = read_index(index_path)
    run_id = record.get("run_id")
    records = [item for item in records if item.get("run_id") != run_id]
    records.append(record)
    records.sort(key=lambda item: str(item.get("updated_at") or ""))
    index_path.write_text(
        "".join(json.dumps(item, ensure_ascii=False, sort_keys=True) + "\n" for item in records),
        encoding="utf-8",
    )


def read_index(index_path: Path) -> list[dict[str, Any]]:
    if not index_path.exists():
        return []
    records: list[dict[str, Any]] = []
    for line in index_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            value = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            records.append(value)
    return records


def write_state_markdown(artifacts_root: Path, limit: int = 20) -> None:
    records = read_index(artifacts_root / "index.jsonl")
    recent = list(reversed(records[-limit:]))
    open_items = [item for item in recent if item.get("status") != "PASSED"]

    lines = [
        "# AI Loop State",
        "",
        "This file is generated by AI Loop as cross-run memory.",
        "",
        f"Updated: {now_iso()}",
        "",
        "## Open Items",
        "",
    ]
    if open_items:
        lines.extend(format_record_bullets(open_items))
    else:
        lines.append("- No open failed or incomplete runs in the recent window.")

    lines.extend(["", "## Recent Runs", ""])
    if recent:
        lines.extend(format_record_bullets(recent))
    else:
        lines.append("- No runs recorded yet.")

    (artifacts_root / "LOOP_STATE.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def format_record_bullets(records: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    for item in records:
        error = f", error={item.get('error_code')}" if item.get("error_code") else ""
        lines.append(
            f"- `{item.get('run_id')}` [{item.get('mode')}] {item.get('status')}{error} "
            f"task=`{item.get('task_file')}` summary=`runs/{item.get('summary_path')}`"
        )
    return lines
