#!/usr/bin/env bash
set -euo pipefail

show_help() {
  cat <<'HELP'
Usage: scripts/phase-d-closeout-check.sh --closeout-json <file> [options]

Validate a Phase D closeout package generated by phase-d-closeout.sh.

Options:
  --closeout-json <file> Phase D closeout JSON, required
  --output <file>        Optional Markdown output path
  --json-output <file>   Optional JSON output path
  -h, --help             Show this help

This script is local-only and read-only.
HELP
}

closeout_json=""
output_file=""
json_output_file=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --closeout-json)
      closeout_json="${2:-}"; shift 2 ;;
    --output)
      output_file="${2:-}"; shift 2 ;;
    --json-output)
      json_output_file="${2:-}"; shift 2 ;;
    -h|--help)
      show_help; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      show_help
      exit 2 ;;
  esac
done

if [[ -z "$closeout_json" ]]; then
  echo "--closeout-json is required" >&2
  show_help
  exit 2
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

json_report="$(python3 - <<'PY' "$closeout_json"
import datetime as dt
import json
import sys
from pathlib import Path

closeout_path = Path(sys.argv[1])
checks = []
def add(name, status, detail=""):
    checks.append({"name": name, "status": status, "detail": detail})

add("closeout_json_exists", "PASSED" if closeout_path.is_file() else "FAILED", str(closeout_path))
try:
    closeout = json.loads(closeout_path.read_text(encoding="utf-8"))
    add("closeout_json_parse", "PASSED", "")
except Exception as exc:
    closeout = {}
    add("closeout_json_parse", "FAILED", str(exc))

required_fields = ["source_run_id", "case_id", "memory_case_draft", "memory_index_entry", "memory_promote_dry_run", "memory_quality", "review_command", "execute_command", "result", "side_effects"]
missing = [field for field in required_fields if field not in closeout or closeout.get(field) in (None, "")]
add("required_fields", "PASSED" if not missing else "FAILED", ", ".join(missing))
for field in ["memory_case_draft", "memory_index_entry", "memory_promote_dry_run", "memory_quality"]:
    value = closeout.get(field)
    add(f"artifact:{field}", "PASSED" if value and Path(value).is_file() and Path(value).stat().st_size > 0 else "FAILED", str(value))

promote_result = "UNKNOWN"
promote_side_effects = None
promote_path = closeout.get("memory_promote_dry_run")
if promote_path and Path(promote_path).is_file():
    promote = json.loads(Path(promote_path).read_text(encoding="utf-8"))
    promote_result = promote.get("result")
    promote_side_effects = promote.get("side_effects")
add("promote_dry_run_passed", "PASSED" if promote_result == "PASSED" else "FAILED", str(promote_result))
add("promote_no_side_effects", "PASSED" if promote_side_effects == [] else "FAILED", str(promote_side_effects))

quality_result = "UNKNOWN"
quality_path = closeout.get("memory_quality")
if quality_path and Path(quality_path).is_file():
    quality = json.loads(Path(quality_path).read_text(encoding="utf-8"))
    quality_result = quality.get("result")
add("memory_quality_passed", "PASSED" if quality_result == "PASSED" else "FAILED", str(quality_result))
add("closeout_result", "PASSED" if closeout.get("result") == "PASSED" else "FAILED", str(closeout.get("result")))
add("closeout_no_side_effects", "PASSED" if closeout.get("side_effects") == [] else "FAILED", str(closeout.get("side_effects")))
add("review_command", "PASSED" if "memory-review-state.sh" in str(closeout.get("review_command")) else "FAILED", str(closeout.get("review_command")))
add("execute_command_guarded", "PASSED" if "memory-promote-draft.sh" in str(closeout.get("execute_command")) and "--execute" in str(closeout.get("execute_command")) else "FAILED", str(closeout.get("execute_command")))

failed = [check for check in checks if check["status"] != "PASSED"]
report = {
    "schema_version": 1,
    "generated_at": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
    "closeout_json": str(closeout_path),
    "result": "PASSED" if not failed else "FAILED",
    "failed_checks": len(failed),
    "checks": checks,
}
print(json.dumps(report, ensure_ascii=False, indent=2))
if failed:
    raise SystemExit(1)
PY
)"

markdown_report="$(python3 - <<'PY' "$json_report"
import json
import sys
report = json.loads(sys.argv[1])
print(f"""# Phase D Closeout Check

## Summary

- Generated at: {report['generated_at']}
- Closeout JSON: {report['closeout_json']}
- Result: {report['result']}
- Failed checks: {report['failed_checks']}

## Checks

| Check | Status | Detail |
|---|---|---|""")
for check in report["checks"]:
    detail = str(check.get("detail") or "").replace("|", "-")
    print(f"| {check['name']} | {check['status']} | {detail} |")
PY
)"

if [[ -n "$json_output_file" ]]; then
  mkdir -p "$(dirname "$json_output_file")"
  printf '%s\n' "$json_report" > "$json_output_file"
  echo "phase_d_closeout_check_json: $json_output_file"
fi
if [[ -n "$output_file" ]]; then
  mkdir -p "$(dirname "$output_file")"
  printf '%s\n' "$markdown_report" > "$output_file"
  echo "phase_d_closeout_check_report: $output_file"
fi
if [[ -z "$json_output_file" && -z "$output_file" ]]; then
  printf '%s\n' "$markdown_report"
fi
